topics:
    microphone: 'mic_data'
    voiceData: 'voice_data'
    voiceText: 'voice_txt'
    outputText: 'output_text'
    micStatus:  'mic_status'


nodes:
    voiceRecorder: 'voice_recorder_node'
    asr: 'speech_recognition'
    reidentification: 'reidentification_node'
    nluServer: 'nlu_service'
    nluInterface: 'nlu_interface'
    pyTts: 'py_tts'
    pepperTts: 'pepper_tts'
    ttsInterface: 'tts_interface'
    

settings:
    language: 'en-US'
    sampleRate: 16000
    chunkSize: 1024
    calibrationTime: 3
    energyThreshold: 100
    identificationThreshold: 0.75
    numFbanks: 64

models:
    defaults: 'models/deep_speaker.h5'

nlu:
    serverUrl: 'http://localhost:5002/webhooks/rest/webhook'

interfaceType:
    terminal: 'terminal'
    voiceTerminal: 'voice_terminal'
    voice: 'voice'

tts:
    speechRate: 150